Repository mintyfrankie/project-elissa, pull requests merged in 2024-01, with the labels that each got.

#1 refactor: overwrite the entire scraping modules with better logic schemas
  README.md
  main.py
  mongodb/client.py
  mongodb/items.py
  poetry.lock
  pyproject.toml
  scraping/__init__.py
  scraping/base.py
  scraping/common.py
  scraping/interfaces.py
  scraping/spiders/product_page.py
  scraping/spiders/review_page.py
  scraping/spiders/search_page.py
  scraping/utils/__init__.py
  scraping/utils/common.py
  scraping/utils/constants.py
  scraping/utils/items.py
  scraping/utils/spiders.py
  scripts/__init__.py
  scripts/converter.py
  tests/conftest.py
  tests/dashboard/test_dashboard.py
  tests/mongodb/test_mongodb.py
  tests/scraping/test_antirobot.py
  tests/scraping/test_product_page.py
  tests/scraping/test_review_page.py
  tests/scraping/test_search_page.py
Labels: size/XXL

#2 fix: overhaul review scraper for review cards outside of France
  README.md
  scraping/spiders/review_page.py
  tests/conftest.py
  tests/scraping/test_review_page.py
Labels: size/M

#3 Refactor scraping modules
  main.py
  mongodb/client.py
  mongodb/interfaces.py
  scraping/__init__.py
  scraping/base.py
  scraping/common.py
  scraping/interfaces.py
  scraping/spiders/product_page.py
  scraping/spiders/review_page.py
  scraping/spiders/search_page.py
Labels: size/L

#10 README.md
  README.md
Labels: size/S

#11 Add API module
  api/__init__.py
  api/demo.py
  api/main.py
  poetry.lock
  pyproject.toml
Labels: size/L

#12 Update README.md
  README.md
Labels: size/XS

#13 feat(dashboard): add viable prototype
  dashboard/__init__.py
  dashboard/hello.py
  dashboard/main.py
  data/dashboard.csv
  data/products.csv
  data/scores.csv
  main.py
  scraping/interfaces.py
Labels: size/XXL
